apiVersion: v1
kind: Service
metadata:
  name: excalidraw-complete-service
  namespace: excalidraw-complete
spec:
  selector:
    app: excalidraw-complete
  ports:
    - protocol: TCP
      port: 80
      targetPort: excalidraw-port
      name: excalidraw-port

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: excalidraw-complete-sqlite-pv-claim
  namespace: excalidraw-complete
  labels:
    app: excalidraw-complete
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excalidraw-complete
  namespace: excalidraw-complete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excalidraw-complete
  template:
    metadata:
      labels:
        app: excalidraw-complete
    spec:
      imagePullSecrets:
      - name: excalidraw-complete-pull-secret
      containers:
      - name: excalidraw-complete
        image: ghcr.io/jmsaruc/excalidraw-complete:latest
        ports:
        - containerPort: 3002
          name: excalidraw-port
        readinessProbe:
          httpGet:
            path: /
            port: excalidraw-port
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: STORAGE_TYPE
          value: "sqlite"
        - name: DATA_SOURCE_NAME
          value: "/app/db-data/excalidraw.db"
        - name: LOCAL_STORAGE_PATH
          value: "/app/db-data"
        - name: VITE_FRONTEND_URL
          value: "https://excalidraw.helloworld2.net"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3002"
        - name: LOG_LEVEL
          value: "info"
        volumeMounts:
        - mountPath: /app/db-data
          name: excalidraw-complete-sqlite-persistent-storage
      volumes:
      - name: excalidraw-complete-sqlite-persistent-storage
        persistentVolumeClaim:
          claimName: excalidraw-complete-sqlite-pv-claim

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excalidraw-complete-ingress
  namespace: excalidraw-complete
  labels:
    name: excalidraw-complete
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: excalidraw.helloworld2.net
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: excalidraw-complete-service
                port:
                  name: excalidraw-port
  tls:
  - hosts:
    - excalidraw.helloworld2.net
    secretName: excalidraw-complete-tls-secret