apiVersion: v1
kind: Service
metadata:
  name: {{include "excalidraw-complete.fullname" .}}
  labels: {{- include "excalidraw-complete.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{.Values.service.type}}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ default "80" .Values.service.port}}
      targetPort: excalidraw-port
      protocol: TCP
      name: http
  selector: {{- include "excalidraw-complete.selectorLabels" . | nindent 4}}